# example config originally a json file
"rm_weight": 1.0
"topk": 10
"mode": "greedy"
"sample_temp": null
"debug" : False
"max_iters": 5
# specifying model names
#"llm": "lomahony/eleuther-pythia6.9b-hh-dpo"
"llm": "Salesforce/LLaMA-3-8B-SFR-Iterative-DPO-R"

#"rm": "usvsnsp/pythia-6.9b-rm-full-hh-rlhf"
"rm": "Salesforce/LLaMA-3-8B-SFR-RM-R"
"rm2": "usvsnsp/pythia-6.9b-rm-full-hh-rlhf"
"critic_use_tq": True 
# "cache_dir" : "/fs/nexus-scratch/jianyu34/.cache/huggingface"
